// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:lockin/core/models/goal.dart';
import 'package:lockin/core/models/habit.dart';
import 'package:lockin/core/models/habit_category.dart';
import 'package:lockin/core/models/journal.dart';
import 'package:lockin/core/models/rule.dart';
import 'package:lockin/core/models/session.dart';
import 'package:lockin/core/models/task.dart';
import 'package:lockin/features/xp/xp_models.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GoalAdapter());
    registerAdapter(HabitAdapter());
    registerAdapter(HabitCategoryAdapter());
    registerAdapter(JournalAdapter());
    registerAdapter(MilestoneAdapter());
    registerAdapter(RewardAdapter());
    registerAdapter(RewardTypeAdapter());
    registerAdapter(RuleAdapter());
    registerAdapter(SessionAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(XPProfileAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GoalAdapter());
    registerAdapter(HabitAdapter());
    registerAdapter(HabitCategoryAdapter());
    registerAdapter(JournalAdapter());
    registerAdapter(MilestoneAdapter());
    registerAdapter(RewardAdapter());
    registerAdapter(RewardTypeAdapter());
    registerAdapter(RuleAdapter());
    registerAdapter(SessionAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(XPProfileAdapter());
  }
}
